spring:
  profiles.active: development

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/integridad
    username: postgres
    password: postgres
    
email:
    username: Soporte.tecnico1@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <Soporte.tecnico1@mrzolutions.com>

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: production
  datasource:
    url: zzzz
    username: xxxx
    password: yyyyyyyy

email:
    username: Soporte.tecnico1@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <Soporte.tecnico1@mrzolutions.com>