spring:
  profiles.active: development

---
spring:
  jpa:
    hibernate:
      ddl-auto: none
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/integridad
    username: postgres
    password: postgres
    
email:
    username: facturacionmrz@gmail.com
    pass: Hijodedios.3
    emailFrom: Integridad - MrZolutions <desarrollo.integridad@mrzolutions.com>

---
spring:
  jpa:
    hibernate:
      ddl-auto: none
      profiles: production
  datasource:
    url: jdbc:postgresql://ec2-34-193-232-231.compute-1.amazonaws.com:5432/db1ae6skr7q6pl?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: rteskdoydvzldn
    password: f718656b38b389047bb5dd22f192492ef2e139a6991e3d583e36ae5a6486c726

email:
    username: facturacionmrz@gmail.com
    pass: Hijodedios.3
    emailFrom: Integridad - MrZolutions <desarrollo.integridad@mrzolutions.com>