spring:
  profiles.active: development

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/integridad
    username: postgres
    password: postgres
    
email:
    username: Soporte.tecnico1@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <Soporte.tecnico1@mrzolutions.com>

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: production
  datasource:
    url: jdbc:postgresql://ec2-54-204-21-226.compute-1.amazonaws.com:5432/dbm55jn6lfeaa4?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: stjfpdbrujaxjv
    password: 6027e96f707dffdb31d71d2268c69641208a49a46d1088a09be518b8e929077d

email:
    username: Soporte.tecnico1@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <Soporte.tecnico1@mrzolutions.com>