spring:
  profiles.active: development

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    
email:
    username: desarrollo.integridad@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <desarrollo.integridad@mrzolutions.com>

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: production
  datasource:
    url: jdbc:postgresql://ec2-18-232-218-200.compute-1.amazonaws.com:5432/d43ebuhb7nme89?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: uohu0g16spl52
    password: pa02a480a39d72dc2574dcd01e6d309c953016f5f244bc88f6e0900450f0eb888

email:
    username: desarrollo.integridad@mrzolutions.com
    pass: hijodedios
    emailFrom: Integridad - MrZolutions <desarrollo.integridad@mrzolutions.com>