spring:
  profiles.active: development

---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/integridad
    username: postgres
    password: postgres

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: production
  datasource:
    url: zzzz
    username: xxxx
    password: yyyyyyyy